INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('New Zealand', 'NZ', 'New Zealand Dollars', 'NZD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Cook Islands', 'CK', 'New Zealand Dollars', 'NZD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Niue', 'NU', 'New Zealand Dollars', 'NZD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Pitcairn', 'PN', 'New Zealand Dollars', 'NZD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Tokelau', 'TK', 'New Zealand Dollars', 'NZD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Australian', 'AU', 'Australian Dollars', 'AUD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Christmas Island', 'CX', 'Australian Dollars', 'AUD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Cocos (Keeling) Islands', 'CC', 'Australian Dollars', 'AUD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Heard and Mc Donald Islands', 'HM', 'Australian Dollars', 'AUD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Kiribati', 'KI', 'Australian Dollars', 'AUD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Nauru', 'NR', 'Australian Dollars', 'AUD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Norfolk Island', 'NF', 'Australian Dollars', 'AUD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Tuvalu', 'TV', 'Australian Dollars', 'AUD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('British Indian Ocean Territory', 'IO', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Guam', 'GU', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Marshall Islands', 'MH', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Micronesia Federated States of', 'FM', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Northern Mariana Islands', 'MP', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Palau', 'PW', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Puerto Rico', 'PR', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Turks and Caicos Islands', 'TC', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('United States', 'US', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('United States Minor Outlying Islands', 'UM', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Virgin Islands (British)', 'VG', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Virgin Islands (US)', 'VI', 'USD', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Hong Kong', 'HK', 'HKD', 'HKD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Canada', 'CA', 'Canadian Dollar', 'CAD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Anguilla', 'AI', 'East Caribbean Dollar', 'XCD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Antigua and Barbuda', 'AG', 'East Caribbean Dollar', 'XCD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Dominica', 'DM', 'East Caribbean Dollar', 'XCD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Grenada', 'GD', 'East Caribbean Dollar', 'XCD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Montserrat', 'MS', 'East Caribbean Dollar', 'XCD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Saint Kitts', 'KN', 'East Caribbean Dollar', 'XCD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Saint Lucia', 'LC', 'East Caribbean Dollar', 'XCD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Saint Vincent Grenadines', 'VC', 'East Caribbean Dollar', 'XCD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Argentina', 'AR', 'Peso', 'ARS', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Bahamas', 'BS', 'Bahamian Dollar', 'BSD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Barbados', 'BB', 'Barbadian Dollar', 'BBD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Bermuda', 'BM', 'Bermudian Dollar', 'BMD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Brunei Darussalam', 'BN', 'Bruneian Dollar', 'BND', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Cayman Islands', 'KY', 'Caymanian Dollar', 'KYD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Chile', 'CL', 'Chilean Peso', 'CLP', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Colombia', 'CO', 'Peso', 'COP', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('El Salvador', 'SV', 'Salvadoran Colon', 'SVC', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Fiji', 'FJ', 'Fijian Dollar', 'FJD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Guyana', 'GY', 'Guyanaese Dollar', 'GYD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Liberia', 'LR', 'Liberian Dollar', 'LRD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Mexico', 'MX', 'Peso', 'MXN', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Namibia', 'NA', 'Dollar', 'NAD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Singapore', 'SG', 'Dollar', 'SGD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Solomon Islands', 'SB', 'Solomon Islands Dollar', 'SBD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Suriname', 'SR', 'Surinamese Guilder', 'SRD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('US Armed Forces', 'USAF', 'US Dollar', 'USD', '$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Bolivia', 'BO', 'Boliviano', 'BOB', '$b');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Uruguay', 'UY', 'Peso', 'UYU', '$U');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 'Sterling', 'GBP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('United Kingdom', 'GB', 'Sterling', 'GBP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Jersey', 'JE', 'Sterling', 'GBP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Egypt', 'EG', 'Egyptian Pound', 'EGP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Falkland Islands (Malvinas)', 'FK', 'Falkland Pound', 'FKP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Gibraltar', 'GI', 'Gibraltar Pound', 'GIP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Lebanon', 'LB', 'Lebanese Pound', 'LBP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Syrian Arab Republic', 'SY', 'Syrian Pound', 'SYP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Guernsey', 'GG', 'Guernsey pound', 'GGP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Isle of Man', 'IM', 'Manx pound', 'GBP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Saint Helena', 'SH', 'Saint Helena pound', 'GBP', '£');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Japan', 'JP', 'Japanese Yen', 'JPY', '¥');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('China', 'CN', 'Yuan Renminbi', 'CNY', '¥');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Afghanistan', 'AF', 'Afghani', 'AFN', '؋');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Thailand', 'TH', 'Baht', 'THB', '฿');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Cambodia', 'KH', 'Riel', 'KHR', '៛');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Costa Rica', 'CR', 'Costa Rican Colon', 'CRC', '₡');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Nigeria', 'NG', 'Naira', 'NGN', '₦');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Korea North', 'KP', 'Won', 'KPW', '₩');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Korea South', 'KR', 'Won', 'KRW', '₩');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Israel', 'IL', 'Shekel', 'ILS', '₪');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Vietnam', 'VN', 'Dong', 'VND', '₫');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('American Samoa', 'AS', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Andorra', 'AD', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Austria', 'AT', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Belgium', 'BE', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Finland', 'FI', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('France', 'FR', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('French Guiana', 'GF', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('French Southern Territories', 'TF', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Germany', 'DE', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Greece', 'GR', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Guadeloupe', 'GP', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Ireland', 'IE', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Italy', 'IT', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Luxembourg', 'LU', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Martinique', 'MQ', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Mayotte', 'YT', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Monaco', 'MC', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Netherlands', 'NL', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Portugal', 'PT', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Reunion', 'RE', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Samoa', 'WS', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('San Marino', 'SM', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Slovenia', 'SI', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Spain', 'ES', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Vatican City State (Holy See)', 'VA', 'Euros', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Aland Islands', 'AX', 'Euro', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Montenegro', 'ME', 'Euro', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Saint Barthelemy', 'BL', 'Euro', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Saint Pierre and Miquelon', 'PM', 'Euro', 'EUR', '€');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Lao PeopleÕs Democratic Republic', 'LA', 'Kip', 'LAK', '₭');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Laos', 'LA', 'Lao kip', 'LAK', '₭');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Mongolia', 'MN', 'Tugrik', 'MNT', '₮');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Cuba', 'CU', 'Cuban Peso', 'CUP', '₱');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Ukraine', 'UA', 'Hryvnia', 'UAH', '₴');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Mauritius', 'MU', 'Mauritian Rupee', 'MUR', '₨');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Nepal', 'NP', 'Nepalese Rupee', 'NPR', '₨');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Pakistan', 'PK', 'Rupee', 'PKR', '₨');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Seychelles', 'SC', 'Rupee', 'SCR', '₨');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Sri Lanka', 'LK', 'Rupee', 'LKR', '₨');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Iran (Islamic Republic of)', 'IR', 'Iranian Rial', 'IRR', '﷼');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Oman', 'OM', 'Sul Rial', 'OMR', '﷼');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Qatar', 'QA', 'Rial', 'QAR', '﷼');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Saudi Arabia', 'SA', 'Riyal', 'SAR', '﷼');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Yemen', 'YE', 'Rial', 'YER', '﷼');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Panama', 'PA', 'Balboa', 'PAB', 'B/.');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Venezuela', 'VE', 'Bolivar', 'VEF', 'Bs');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Belize', 'BZ', 'Belizean Dollar', 'BZD', 'BZ$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Nicaragua', 'NI', 'Cordoba Oro', 'NIO', 'C$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Liechtenstein', 'LI', 'Swiss Franc', 'CHF', 'CHF');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Switzerland', 'CH', 'Swiss Franc', 'CHF', 'CHF');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Hungary', 'HU', 'Forint', 'HUF', 'Ft');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Aruba', 'AW', 'Netherlands Antilles Guilder', 'ANG', 'ƒ');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Netherlands Antilles', 'AN', 'Netherlands Antilles Guilder', 'ANG', 'ƒ');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Saint Martin (French part)', 'MF', 'Netherlands Antillean guilder', 'ANG', 'ƒ');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Paraguay', 'PY', 'Guarani', 'PYG', 'Gs');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Jamaica', 'JM', 'Jamaican Dollar', 'JMD', 'J$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Czech Republic', 'CZ', 'Koruna', 'CZK', 'Kč');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Bosnia and Herzegovina', 'BA', 'Bosnia and Herzegovina convertible mark', 'BAM', 'KM');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Croatia (Hrvatska)', 'HR', 'Croatian Dinar', 'HRK', 'kn');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Bouvet Island', 'BV', 'Norwegian Krone', 'NOK', 'kr');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Norway', 'NO', 'Norwegian Krone', 'NOK', 'kr');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Svalbard and Jan Mayen Islands', 'SJ', 'Norwegian Krone', 'NOK', 'kr');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Denmark', 'DK', 'Danish Krone', 'DKK', 'kr');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Faroe Islands', 'FO', 'Danish Krone', 'DKK', 'kr');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Greenland', 'GL', 'Danish Krone', 'DKK', 'kr');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Iceland', 'IS', 'Icelandic Krona', 'ISK', 'kr');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Sweden', 'SE', 'Krona', 'SEK', 'kr');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Honduras', 'HN', 'Lempira', 'HNL', 'L');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Romania', 'RO', 'Leu', 'RON', 'lei');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Albania', 'AL', 'Lek', 'ALL', 'Lek');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Latvia', 'LV', 'Lat', 'LVL', 'Ls');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Lithuania', 'LT', 'Lita', 'LTL', 'Lt');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Mozambique', 'MZ', 'Metical', 'MZN', 'MT');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Taiwan', 'TW', 'Dollar', 'TWD', 'NT$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Botswana', 'BW', 'Pula', 'BWP', 'P');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Belarus', 'BY', 'Belarus Ruble', 'BYR', 'p.');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Philippines', 'PH', 'Peso', 'PHP', 'Php');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Guatemala', 'GT', 'Quetzal', 'GTQ', 'Q');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('South Africa', 'ZA', 'Rand', 'ZAR', 'R');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Brazil', 'BR', 'Brazil', 'BRL', 'R$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Malaysia', 'MY', 'Ringgit', 'MYR', 'RM');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Bhutan', 'BT', 'Indian Rupee', 'INR', 'Rp');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('India', 'IN', 'Indian Rupee', 'INR', 'Rp');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('East Timor', 'TP', 'Indonesian Rupiah', 'IDR', 'Rp');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Indonesia', 'ID', 'Indonesian Rupiah', 'IDR', 'Rp');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Somalia', 'SO', 'Shilling', 'SOS', 'S');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Peru', 'PE', 'Nuevo Sol', 'PEN', 'S/.');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Turkey', 'TR', 'Lira', 'TRY', 'TL');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Trinidad and Tobago', 'TT', 'Trinidad and Tobago Dollar', 'TTD', 'TT$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Zimbabwe', 'ZW', 'Zimbabwe Dollar', 'ZWD', 'Z$');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Poland', 'PL', 'Zloty', 'PLN', 'zł');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Macedonia', 'MK', 'Denar', 'MKD', 'ден');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Serbia', 'RS', 'Serbian dinar', 'RSD', 'Дин.');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Bulgaria', 'BG', 'Lev', 'BGN', 'лв');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Kazakhstan', 'KZ', 'Tenge', 'KZT', 'лв');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Kyrgyzstan', 'KG', 'Som', 'KGS', 'лв');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Uzbekistan', 'UZ', 'Som', 'UZS', 'лв');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Azerbaijan', 'AZ', 'Manat', 'AZN', 'ман');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Russian Federation', 'RU', 'Ruble', 'RUB', 'руб');
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Algeria', 'DZ', 'Algerian Dinar', 'DZD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Armenia', 'AM', 'Dram', 'AMD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Bahrain', 'BH', 'Bahraini Dinar', 'BHD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Bangladesh', 'BD', 'Taka', 'BDT', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Benin', 'BJ', 'CFA Franc BCEAO', 'XOF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Burkina Faso', 'BF', 'CFA Franc BCEAO', 'XOF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Guinea-Bissau', 'GW', 'CFA Franc BCEAO', 'XOF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Ivory Coast', 'CI', 'CFA Franc BCEAO', 'XOF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Mali', 'ML', 'CFA Franc BCEAO', 'XOF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Niger', 'NE', 'CFA Franc BCEAO', 'XOF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Senegal', 'SN', 'CFA Franc BCEAO', 'XOF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Togo', 'TG', 'CFA Franc BCEAO', 'XOF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Burundi', 'BI', 'Burundi Franc', 'BIF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Cameroon', 'CM', 'CFA Franc BEAC', 'XAF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Central African Republic', 'CF', 'CFA Franc BEAC', 'XAF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Chad', 'TD', 'CFA Franc BEAC', 'XAF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Congo Republic of the Democratic', 'CG', 'CFA Franc BEAC', 'XAF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Equatorial Guinea', 'GQ', 'CFA Franc BEAC', 'XAF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Gabon', 'GA', 'CFA Franc BEAC', 'XAF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Cape Verde', 'CV', 'Escudo', 'CVE', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Comoros', 'KM', 'Comoran Franc', 'KMF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Congo-Brazzaville', 'CD', 'Congolese Frank', 'CDF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Cyprus', 'CY', 'Cypriot Pound', 'CYP', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Djibouti', 'DJ', 'Djiboutian Franc', 'DJF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Dominican Republic', 'DO', 'Dominican Peso', 'DOP', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Ecuador', 'EC', 'Sucre', 'ECS', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Eritrea', 'ER', 'Ethiopian Birr', 'ETB', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Ethiopia', 'ET', 'Ethiopian Birr', 'ETB', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Estonia', 'EE', 'Estonian Kroon', 'EEK', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('French Polynesia', 'PF', 'CFP Franc', 'XPF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('New Caledonia', 'NC', 'CFP Franc', 'XPF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Wallis and Futuna Islands', 'WF', 'CFP Franc', 'XPF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Gambia', 'GM', 'Dalasi', 'GMD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Georgia', 'GE', 'Lari', 'GEL', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Guinea', 'GN', 'Guinean Franc', 'GNF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Haiti', 'HT', 'Gourde', 'HTG', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Iraq', 'IQ', 'Iraqi Dinar', 'IQD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Jordan', 'JO', 'Jordanian Dinar', 'JOD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Kenya', 'KE', 'Kenyan Shilling', 'KES', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Kuwait', 'KW', 'Kuwaiti Dinar', 'KWD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Lesotho', 'LS', 'Loti', 'LSL', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Libyan Arab Jamahiriya', 'LY', 'Libyan Dinar', 'LYD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Macau', 'MO', 'Pataca', 'MOP', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Madagascar', 'MG', 'Malagasy Franc', 'MGA', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Malawi', 'MW', 'Malawian Kwacha', 'MWK', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Maldives', 'MV', 'Rufiyaa', 'MVR', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Malta', 'MT', 'Maltese Lira', 'MTL', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Mauritania', 'MR', 'Ouguiya', 'MRO', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Moldova Republic of', 'MD', 'Leu', 'MDL', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Morocco', 'MA', 'Dirham', 'MAD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Western Sahara', 'EH', 'Dirham', 'MAD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Myanmar', 'MM', 'Kyat', 'MMK', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Papua New Guinea', 'PG', 'Kina', 'PGK', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Rwanda', 'RW', 'Rwanda Franc', 'RWF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Sao Tome and Principe', 'ST', 'Dobra', 'STD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Sierra Leone', 'SL', 'Leone', 'SLL', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Slovakia (Slovak Republic)', 'SK', 'Koruna', 'SKK', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Sudan', 'SD', 'Dinar', 'SDG', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Swaziland', 'SZ', 'Lilangeni', 'SZL', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Tajikistan', 'TJ', 'Tajikistan Ruble', 'TJS', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Tanzania', 'TZ', 'Shilling', 'TZS', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Tonga', 'TO', 'PaÕanga', 'TOP', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Tunisia', 'TN', 'Tunisian Dinar', 'TND', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Turkmenistan', 'TM', 'Manat', 'TMT', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Uganda', 'UG', 'Shilling', 'UGX', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('United Arab Emirates', 'AE', 'Dirham', 'AED', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Vanuatu', 'VU', 'Vatu', 'VUV', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Zambia', 'ZM', 'Kwacha', 'ZMK', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Angola', 'AO', 'Angolan kwanza', 'AOA', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Antarctica', 'AQ', 'Antarctican dollar', 'AQD', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Congo (Kinshasa)', 'CD', 'Congolese Frank', 'CDF', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Ghana', 'GH', 'Ghana cedi', 'GHS', null);
INSERT INTO country_currencies (country, CountryCode, currency, code, symbol) VALUES ('Macao S.A.R.', 'MO', 'Macanese pataca', 'MOP', null);